---
- name: Capture logs from Kubernetes pod and upload to Minio
  hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes
    - amazon.aws
  vars:
    namespace: "{{ namespace }}"
    pod_name: "{{ pod_name }}"
    minio_bucket: "your-minio-bucket"
    minio_access_key: "{{ minio_access_key }}"
    minio_secret_key: "{{ minio_secret_key }}"
    minio_endpoint_url: "http://minio-service:9000"  # Replace with your Minio service URL
    log_file_path: "/tmp/{{ pod_name }}_logs.txt"

  tasks:
    - name: Ensure kubectl is installed
      command: "which kubectl"
      register: kubectl_check
      failed_when: kubectl_check.rc != 0

    - name: Get the list of containers in the pod
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
        name: "{{ pod_name }}"
      register: pod_info

    - name: Fetch logs from each container
      command: >
        kubectl logs -n {{ namespace }} {{ pod_name }} -c {{ item.name }}
      loop: "{{ pod_info.resources[0].spec.containers }}"
      register: pod_logs

    - name: Save logs to file
      copy:
        content: "{{ pod_logs.results | map(attribute='stdout') | join('\n') }}"
        dest: "{{ log_file_path }}"

    - name: Upload logs to Minio
      amazon.aws.aws_s3:
        bucket: "{{ minio_bucket }}"
        object: "{{ pod_name }}_logs.txt"
        src: "{{ log_file_path }}"
        mode: put
      vars:
        aws_access_key: "{{ minio_access_key }}"
        aws_secret_key: "{{ minio_secret_key }}"
        s3_url: "{{ minio_endpoint_url }}"
